stages:
  train:
    cmd: python -m coffeecv.train_baseline
    deps:
      - coffeecv
      - dataset/2026-08-07__box_pictures_all_classes
      - dataset/classes.txt
    params:
      - params.yaml:
    outs:
      - outputs/checkpoints/best.pt
      - outputs/checkpoints/last.pt
    metrics:
      - outputs/metrics.json:
          cache: false
    plots:
      - outputs/history.json:
          x: epoch
          y: train_loss
      - outputs/history.json:
          x: epoch
          y: val_loss
      - outputs/history.json:
          x: epoch
          y: val_macro_f1
      - outputs/predictions_val.csv:
          template: confusion
          x: true_label
          y: pred_label
      - outputs/predictions_test.csv:
          template: confusion
          x: true_label
          y: pred_label
